# Generated by Django 2.2.3 on 2019-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartcervUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='image title')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
