# Generated by Django 2.2.2 on 2019-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartcervUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_preamble', models.TextField(verbose_name='choose image')),
                ('upload', models.FileField(upload_to='smartcerv_patient_pictures')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
